language: r
sudo: required
cache: packages
services:
  - docker
r_packages:
  - covr
  # only needed during the 3.4 -> 3.5 changeover
  - devtools
r_github_packages:
  - richfitz/httppipe
  - viking/r-yaml
before_script:
  - docker pull hello-world
  - docker pull alpine
  - docker pull alpine:3.1
  - docker pull bfirsh/reticulate-splines
  - docker pull nginx
  - docker pull postgres
  - docker pull bobrik/socat:latest
  - (cd tests/testthat/images && ./build.sh)
  - cp vignettes_src/*.Rmd vignettes
after_success:
  - Rscript -e 'covr::codecov()'
env:
  - STEVEDORE_TEST_USE_DOCKER=true
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - python-numpy
      - python-requests
      - libhiredis-dev
