language: r
sudo: required
cache: packages
services:
  - docker
r_packages:
  - covr
r_github_packages:
  - richfitz/httppipe
before_script:
  - docker pull hello-world
  - docker pull alpine
  - docker pull alpine:3.1
  - docker pull bfirsh/reticulate-splines
  - docker pull nginx
  - (cd tests/testthat/images && ./build.sh)
after_install:
  # Force old version for now
  - Rscript -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/yaml/yaml_2.1.16.tar.gz", repos = NULL)'
after_success:
  - Rscript -e 'covr::codecov()'
env:
  - STEVEDORE_TEST_USE_DOCKER=true
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - python-numpy
      - python-requests
